name: mambatts
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - numpy=2.2.5
  - einops=0.8.1
  - filelock=3.20.0
  - fsspec=2025.10.0
  - huggingface_hub=0.24.0
  - jinja2=3.1.6
  - joblib=1.5.2
  - networkx=3.4.2
  - nltk=3.9.2
  - packaging=25.0
  - pillow=12.0.0
  - pip
  - pyyaml=6.0.3
  - regex=2025.9.1
  - requests=2.32.5
  - safetensors=0.6.2
  - sympy=1.14.0
  - tokenizers=0.15.1
  - tqdm=4.67.1
  - transformers=4.39.3
  - typing-extensions=4.15.0
  - pip:
      - attrs==25.4.0
      - audioread==3.1.0
      - beautifulsoup4==4.14.2
      - click==8.3.1
      - decorator==5.2.1
      - g2p-en==2.1.0
      - gdown==5.2.0
      - inflect==7.5.0
      - librosa==0.10.1
      - numba==0.62.1
      - phonemizer==3.3.0
      - pooch==1.8.2
      - pyloudnorm==0.1.1
      - pyworld==0.3.5
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - soundfile==0.13.1
      - soxr==1.0.0
      - termcolor==3.2.0
      - unidecode==1.4.0
