name: mambatts
channels:
  - pytorch
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - aom=3.12.1
  - blas=1.0
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - cairo=1.18.4
  - certifi=2025.11.12
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - dav1d=1.2.1
  - einops=0.8.1
  - expat=2.7.3
  - filelock=3.20.0
  - fontconfig=2.15.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.10.0
  - gettext=0.21.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - hf-xet=1.1.8
  - huggingface_hub=0.34.4
  - icu=73.1
  - idna=3.11
  - jinja2=3.1.6
  - joblib=1.5.2
  - jpeg=9f
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libcxx=20.1.8
  - libdeflate=1.22
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.84.4
  - libiconv=1.16
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libpng=1.6.50
  - libtiff=4.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - nltk=3.9.2
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openssl=3.6.0
  - packaging=25.0
  - pcre2=10.46
  - pillow=12.0.0
  - pip=25.3
  - pixman=0.46.4
  - pycparser=2.23
  - pysocks=1.7.1
  - python=3.10.19
  - pytorch=2.5.1
  - pyyaml=6.0.3
  - readline=8.3
  - regex=2025.9.1
  - requests=2.32.5
  - safetensors=0.6.2
  - setuptools=80.9.0
  - sqlite=3.51.0
  - sympy=1.14.0
  - tk=8.6.15
  - tokenizers=0.15.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tqdm=4.67.1
  - transformers=4.39.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - attrs==25.4.0
      - audioread==3.1.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - click==8.3.1
      - csvw==3.7.0
      - decorator==5.2.1
      - distance==0.1.3
      - dlinfo==2.0.0
      - future==1.0.0
      - g2p-en==2.1.0
      - gdown==5.2.0
      - inflect==7.5.0
      - isodate==0.7.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - language-tags==1.2.0
      - lazy-loader==0.4
      - librosa==0.10.1
      - llvmlite==0.45.1
      - more-itertools==10.8.0
      - msgpack==1.1.2
      - ns3-codec==0.2.2
      - numba==0.62.1
      - phonemizer==3.3.0
      - platformdirs==4.5.0
      - pooch==1.8.2
      - pyloudnorm==0.1.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pyworld==0.3.5
      - rdflib==7.4.0
      - referencing==0.37.0
      - rfc3986==1.5.0
      - rpds-py==0.29.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - segments==2.3.0
      - six==1.17.0
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - typeguard==4.4.4
      - unidecode==1.4.0
      - uritemplate==4.2.0
prefix: /Users/henrycorkran/anaconda3/envs/mambatts
